varsExp=( K )
#~ minExp=( 4 )     
#~ maxExp=( 40 ) 
minExp=( 9 )     
maxExp=( 9 )  
increment=( 2 )
folderConf="v1/3s"
defaultVarNames=(s    d   v   K   n)
defaultValues=(  3.0 1.0  1.0 10  200)
nTests=1
